version: 2
updates:
  - package-ecosystem: "github-actions"  # zizmor: ignore[dependabot-cooldown]
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns: ["*"]
    labels:
      - "dependencies"
      - "Skip Changelog"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
