blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://urllib3future.readthedocs.io
    about: Make sure you read the relevant docs
  - name: ❓ Ask on StackOverflow
    url: https://stackoverflow.com/questions/tagged/urllib3
    about: Ask questions about usage in StackOverflow
