package urllib3:p1-fallback;

world command {
  include wasi:clocks/imports@0.2.0;
  include wasi:filesystem/imports@0.2.0;
  include wasi:random/imports@0.2.0;
  include wasi:io/imports@0.2.0;

  import wasi:cli/environment@0.2.0;
  import wasi:cli/exit@0.2.0;
  import wasi:cli/stdin@0.2.0;
  import wasi:cli/stdout@0.2.0;
  import wasi:cli/stderr@0.2.0;
  import wasi:cli/terminal-input@0.2.0;
  import wasi:cli/terminal-output@0.2.0;
  import wasi:cli/terminal-stdin@0.2.0;
  import wasi:cli/terminal-stdout@0.2.0;
  import wasi:cli/terminal-stderr@0.2.0;

  export wasi:cli/run@0.2.0;
}
